apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: python
        command: ["sh", "-c", "cd /tmp/ && git clone https://github.com/cesarvr/demos-webgl demos && cd demos/static/ && echo serving content!! && python -m http.server 8087"]
        ports:
        - containerPort: 8087
        livenessProbe:
          httpGet:
            path: /
            port: 8087
      - name: sidecar
        image: docker-registry.default.svc:5000/web-apps/ambassador
        command: ["sh", "-c", "npm start"]
        ports:
        - containerPort: 8080
